name: ContinuousDeployment

# on push events to master, tagged with a version number
on:
  push:
    branches:
      - master
    tags:
      - 'v*' # 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install twine toml wheel

    # last check if tests work
    - name: Run tests
      run: |
        python -m unittest discover -v test

    - name: Create Release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false

    - name: "package :package: peaksql"
      run: |
        python setup.py sdist bdist_wheel

    - name: "upload to PyPi test :snake:"
      run:
        twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u __token__ -p ${{ secrets.PyPi_test }}
