name: ContinuousDeployment

# TODO branch master (git tag?)
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    # last check if tests work
    - name: Run tests
      run: |
        coverage run -m unittest discover -v test

    - name: upload to PyPi test :snake:
      run:
        twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u __token__ -p ${{ secrets.1PyPi_test }}
