name: Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        os: ['ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.0.2
      with:
       activate-environment: peaksql
       environment-file: environment.yml
       python-version: ${{ matrix.python-version }}

    - name: Install coverage
      shell: bash -l {0}
      run: |
        conda install coverage

    - name: Test 
      run: |
        coverage run -m unittest discover test
        coverage xml
